### ISSUE TITLE
Does not support any modern versions of any IDE

### ISSUE THREAD

**Issue by skylorbeck** [Bryanx/regex-rename-files#10]
title. Please update! This plugin is one of a kind, literally.

**Comment by skylorbeck** [comment]
#9

**Comment by Bryanx** [comment]
Sorry, I haven't had time to look into this yet. Build appears to be failing. If you have time you can create a PR.

**Comment by skylorbeck** [comment]
Hey don't worry about it my dude. I get it. I ended up just opening the jar file from the last release and editing the target version to be the latest. Plugin works fine so far, at least I got what I needed done with it.
