### ISSUE TITLE
Regex can break UI input box

### ISSUE THREAD

**Issue by richardlampitt** [Bryanx/regex-rename-files#12]
### Symptoms:
The text input boxes will not correctly respond to user input at times - particularly when pressing `SHIFT+4` for `$` character.

### IDE: 
PHPStorm 
**Version:** 2021.2.3

**Build:** #PS-212.5457.49
**Runtime version:** 11.0.12+7-b1504.40 amd64
**VM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### Stacktraces:
[stacktraces.txt](https://github.com/Bryanx/regex-rename-files/files/8908704/stacktraces.txt)

**Comment by Bryanx** [comment]
Thanks for creating an issue for this. I will take a look tomorrow.
