### ISSUE TITLE
Support directory selection, recursive search

### ISSUE THREAD

**Issue by BigBallard** [Bryanx/regex-rename-files#20]
## Feature Request

The better the usefulness of this plugin, I would suggest adding the option to include directories in the search and recursively search for files that match the regex.

### Use Case

I have a project with many folders and in those folders I need to update the extension of all those files. With the current implementation I can't include directories in my selection and therefor would require an extensive session of going into a large number of directories to apply these changes.

#### More explicit use case.

A frontend project is being converted from CRA to Vite. React components can be defined in `.,js` files but Vite would require those files extensions be converted to `.jsx` to distinguish between a normal JS file and JSX file. The project has over a dozen directories wide and many directories deep of components files. Ultimately right clicking the components folder and use this plugin would be a major bonus.

**Comment by Bryanx** [comment]
Hi, thanks for the thorough suggestion. I think however you are unaware that this feature is already present. You can already select a directory and rename all nested files/folders.

**Comment by BigBallard** [comment]
Oh, well in that case I think this plugin is not supported in the latest WebStorm version (2022.2.3) (Build #WS-222.4345.14) as I cannot see the option for either a single file or directory.

**Comment by Bryanx** [comment]
That's strange, that version should be supported. I will try to reproduce this tomorrow. Thanks for reporting.

**Comment by BigBallard** [comment]
Please ignore my ignorance. It appears the plugin does work and I did not have my plugins synched. However the option does not not appear for a single file. I right click on a single file and the option does not show, but multiple files or a directory it does. Which I guess makes sense since there is already an built-in option to rename a single file.
Closing.
