### ISSUE TITLE
Incompatible with current IDE versions 2022.3

### ISSUE THREAD

**Issue by TheMen4ce** [Bryanx/regex-rename-files#21]
<img width="304" alt="image" src="https://user-images.githubusercontent.com/9498649/205884444-66bcbd8e-64e1-4448-816f-0c63028f8126.png">

love this plugin. thx for the update :)

**Comment by Bryanx** [comment]
Thanks! I will update it tomorrow.

**Comment by Bryanx** [comment]
Should be resolved.

**Comment by TheMen4ce** [comment]
Legend! Thx 🙏
