### ISSUE TITLE
Doesn't work in 2023.3 builds

### ISSUE THREAD

**Issue by kevinquillen** [Bryanx/regex-rename-files#27]
Plugin does not work in the newest releases:

![image](https://github.com/Bryanx/regex-rename-files/assets/362176/bb2b90eb-78a6-4a96-9790-974fa7448e10)

**Comment by kevinquillen** [comment]
https://github.com/Bryanx/regex-rename-files/blob/main/gradle.properties#L11

**Comment by scharf** [comment]
Please fix this -- does intellij not provide some kind of semantic versioning for the APIs this plugnin depende on?

**Comment by Bryanx** [comment]
I will make a new release tomorrow
