### ISSUE TITLE
Request: option permit overwriting existing files with same name as target renamed files

### ISSUE THREAD

**Issue by nabilmagnus** [Bryanx/regex-rename-files#29]

**Comment by Bryanx** [comment]
I do not understand.. can you be more specific?

**Comment by hemeroc** [comment]
I think I ran into the same issue.
It fails when it renames e.g.
`FooBAR` to `FooBar` with the error that a file with the name already exists. (which in fact it does not ^^)

**Comment by nabilmagnus** [comment]
> I do not understand.. can you be more specific?
@Bryanx exactly same issue as @hemeroc

**Comment by Bryanx** [comment]
Thanks for clarifying, I will take a look

**Comment by Bryanx** [comment]
Thanks for creating this issue, I have created a patch. It should be available in a few days.
