### ISSUE TITLE
PyCharm 2024.1 compatibility

### ISSUE THREAD

**Issue by Eraldo** [Bryanx/regex-rename-files#31]
<img width="324" alt="Screenshot 2024-04-05 at 22 46 55" src="https://github.com/Bryanx/regex-rename-files/assets/73378/d8b096ed-fbc6-4133-94c6-d9d077b32c6d">

Error file in text version:
```
Plugin 'Regex Rename Files' (version '1.2.7') is not compatible with the current version of the IDE, because it requires build 233.* or older but the current build is PY-241.14494.241
```

**Comment by dhkim0225** [comment]
We really need this. @Bryanx

**Comment by Bryanx** [comment]
Thanks for letting me know. I've been meaning to do this, but the build keeps failing. I will fix it later today.

**Comment by Bryanx** [comment]
I've released a new version. It should be published within 2 days.
