### ISSUE TITLE
Not compatible with Android Studio Koala | 2024.1.1 Canary 3

### ISSUE THREAD

**Issue by ydonev** [Bryanx/regex-rename-files#32]
To Reproduce
Steps to reproduce the behaviour:
1.Install latest Android Studio from Canary channel
2. Try to install the plugin

Expected behaviour
The plug in to be installed and working as expected

Actual behaviour
Plug in is not compatible with latest AS and IDE 233.* and cannot be installed

**Comment by Bryanx** [comment]
I've released a new version. It should be published within 2 days.
